"""Add lead_time and season_flag to PriceLog

Revision ID: 4f124afac230
Revises: 
Create Date: 2025-09-23 01:09:30.177635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f124afac230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('season_flag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_log', schema=None) as batch_op:
        batch_op.drop_column('season_flag')
        batch_op.drop_column('lead_time')

    # ### end Alembic commands ###
